spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/Test
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: SuperCuteSecret
  expiration: 3600000