spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT}
  access:
    expiration: 300000
  refresh:
    expiration: 86400000

server:
  port: 443
  ssl:
    key-store-type: JKS
    key-store: classpath:server.jks
    key-store-password: ${SERVERPASS}
    key-alias: server